export const CATEGORIES = [
  'arts',
  'automobiles',
  'books',
  'business',
  'fashion',
  'food',
  'health',
  'home',
  'insider',
  'magazine',
  'movies',
  'nyregion',
  'obituaries',
  'opinion',
  'politics',
  'realestate',
  'science',
  'sports',
  'sundayreview',
  'technology',
  'theater',
  't-magazine',
  'travel',
  'upshot',
  'us',
  'world',
];

export const CATEGORIES_EMOJI = {
  arts: '🎨',
  automobiles: '🚗',
  books: '📚',
  business: '🕴🏻',
  fashion: '👗',
  food: '🍽',
  health: '🧑‍⚕️',
  home: '🏠',
  insider: '💳',
  magazine: '🗞️',
  movies: '🎥',
  nyregion: '🗽',
  obituaries: '🪦',
  opinion: '💭',
  politics: '📋',
  realestate: '🏦',
  science: '🔬',
  sports: '⚽',
  sundayreview: '⭐',
  technology: '💻',
  theater: '🎭',
  't-magazine': '📰',
  travel: '🛫',
  upshot: '💡',
  us: '🇺🇸',
  world: '🌏',
};
